openapi: 3.0.0
info:
  description: sample
  version: 1.0.0
  title: Swagger Petstore
  termsOfSerice: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
- name: pet
  description: Everything about your Pets
  externalDocs:
    description: Find out more
    url: http://swagger.io
- name: store
  description: Access to Petstore orders
- name: user
  description: Operations about user
  externalDocs:
    description: Find out more about our store
    url: http://swagger.io
paths:
  "/pets/{petId}":
    "$ref": "./pets.yaml"
  "/test-post":
    "$ref": "./sample-post.yaml"
  "/test-get":
    "$ref": "./sample-get.yaml"
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://petstore.swagger.io/v2
- url: http://petstore.swagger.io/v2
components:
  requestBodies:
    Pet:
      content:
        application/json:
          schema:
            "$ref": "./schemas/Pet.yaml"
      description: Pet object that needs to be added to the store
      required: true
  securitySchemas:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://petstore.swagger.io/oauth/dialog
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      typs: apiKey
      name: api_key
      in: header
  schemas:
    "$ref": "./schemas/_index.yaml"
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
